// Coordinator Browser Contract — the declared browser-facing REST surface.
//
// Scope: every coordinator-owned route that web-viewer-sample actually calls.
// Proxied /api/governance/* and /api/kit/* payloads are owned upstream and are not
// declared here. Status codes and bodies describe what the handlers emit today,
// as verified by the response-validation seam (src/contract/responseValidation.ts)
// running in enforce mode under the coordinator test suite.
//
// Cross-cutting statuses:
//   401/403 `{detail}` — AuthError from the user auth provider, mapped by the global handler
//   403/429 `{detail}` — operator control guard (IP allowlist / x-operator-token rate limit)
//   400 `{detail: flatten()}` — zod request rejection, mapped by the global handler
import { z } from "zod/v4";
import { defineRoute } from "./route.js";
import {
  anyError,
  detailError,
  errorCodeError,
  namedError,
  readyModelIdParam,
  safeJobIdParam,
  sessionIdParam,
  validationError,
} from "./primitives.js";
import {
  a4HandoffConsumeResponse,
  a4HandoffCreateRequest,
  a4HandoffCreateResponse,
  a4HandoffEvidenceRejected,
} from "./schemas/a4Handoff.js";
import {
  conversionControlRequest,
  conversionPrioritizeResponse,
  conversionQualityMetricsResponse,
  conversionRecordsResponse,
  conversionRetryConflict,
  conversionRetryResponse,
  conversionTriggerRequest,
  conversionTriggerResponse,
  readyReviewIntentRequest,
  readyReviewSessionResponse,
} from "./schemas/conversion.js";
import {
  ifcReadyDetailResponse,
  ifcReadyDownloadFailed,
  ifcReadyIntakeAccepted,
  ifcReadyIntakeReplay,
  ifcReadyIntakeRequest,
  ifcReadyListResponse,
  ifcReadyReviewSessionConflict,
  ifcReadyReviewSessionOpen,
} from "./schemas/ifcReady.js";
import {
  lineageConversionReport,
  lineageConversionReportDifferences,
  lineageConversionReportList,
  lineageDifferenceSet,
  sourceBundleLookupResponse,
} from "./schemas/lineage.js";
import {
  minioObjectsResponse,
  minioWatchStatusView,
  minioWatchToggleRequest,
} from "./schemas/minio.js";
import { callbackOutboxSummary, issueSnapshotAccepted, issueSnapshotRequest } from "./schemas/outbox.js";
import { runtimeStatusResponse } from "./schemas/runtime.js";
import {
  closeSessionRequest,
  closedSessionPage,
  createSessionRequest,
  firstFrameResponse,
  queuedForInstanceConflict,
  recreateNotRebuildableError,
  recreateSessionRequest,
  recreateSessionResponse,
  reviewSession,
  sessionActivityRequest,
  sessionActivityResponse,
  sessionIdlePolicyResponse,
  sessionIdlePolicyUpdateRequest,
  sessionIdleStatusResponse,
  streamConfigResponse,
} from "./schemas/sessions.js";
import {
  stageBindingCancellationRequest,
  stageBindingCancellationResponse,
  stageBindingNotAbortableError,
  stageBindingPreauthorizationRequest,
  stageBindingPreauthorizationResponse,
} from "./schemas/stageBinding.js";
import {
  claimViewerLeaseRequest,
  claimViewerLeaseResponse,
  heartbeatViewerLeaseRequest,
  heartbeatViewerLeaseResponse,
  publicViewerLease,
  releaseViewerLeaseRequest,
  viewerLeaseStatusResponse,
} from "./schemas/viewerLeases.js";

import {
  cfdOverlayRegistrationRequest,
  cfdOverlayRegistrationResponse,
  cfdOverlayRemovalResponse,
  cfdEstimate,
  cfdEstimateRequest,
  cfdOptionsDocument,
  cfdRunCreateRequest,
  cfdRunDetailResponse,
  cfdRunExclusions,
  cfdRunId,
  cfdRunListResponse,
  cfdRunListQuery,
  cfdRunResult,
  cfdRunStatusDocument,
  cfdBindingIdParam,
  cfdFindingRequest,
  cfdFindingResponse,
} from "./schemas/cfd.js";

const sessionParams = z.object({ sessionId: sessionIdParam });
const leaseParams = z.object({ sessionId: sessionIdParam, leaseId: z.string().min(1).max(200) });
const cfdRunParams = z.object({ runId: cfdRunId });
const cfdOverlayParams = z.object({ sessionId: sessionIdParam, bindingId: cfdBindingIdParam });
const requestValidation = z.union([validationError, detailError]);
/** AuthError from the user auth provider (mapped by the global handler). */
const userAuth = { 401: detailError, 403: detailError } as const;
/** Operator control guard: IP allowlist / operator token / per-IP rate limit. */
const operatorGuard = { 403: detailError, 429: detailError } as const;

export const browserContract = [
  // ── Runtime ────────────────────────────────────────────────────────────────
  defineRoute({
    operationId: "getRuntimeStatus",
    method: "get",
    path: "/api/runtime/status",
    summary: "Coordinator-visible runtime summary for operator surfaces.",
    tags: ["runtime"],
    responses: { 200: runtimeStatusResponse },
  }),
  defineRoute({
    operationId: "getSessionIdlePolicy",
    method: "get",
    path: "/api/runtime/session-idle-policy",
    summary: "Read the live session idle-reclaim policy.",
    tags: ["runtime"],
    responses: { 200: sessionIdlePolicyResponse },
  }),
  defineRoute({
    operationId: "updateSessionIdlePolicy",
    method: "put",
    path: "/api/runtime/session-idle-policy",
    summary: "Operator live override of the session idle timeout (revision + process epoch guarded).",
    tags: ["runtime"],
    auth: "operator",
    body: sessionIdlePolicyUpdateRequest,
    responses: { 200: sessionIdlePolicyResponse, 400: detailError, 409: detailError, ...operatorGuard },
  }),

  // ── Review Sessions ────────────────────────────────────────────────────────
  defineRoute({
    operationId: "createReviewSession",
    method: "post",
    path: "/api/review-sessions",
    summary: "Create a Review Session (explicit create or legacy single-session).",
    tags: ["review-sessions"],
    body: createSessionRequest,
    responses: {
      200: reviewSession,
      400: requestValidation,
      409: z.union([namedError, queuedForInstanceConflict]),
      502: namedError,
    },
  }),
  defineRoute({
    operationId: "listClosedReviewSessions",
    method: "get",
    path: "/api/review-sessions",
    summary: "Page through archived (closed) Review Sessions with rebuildability.",
    tags: ["review-sessions"],
    query: z.object({
      status: z.literal("closed"),
      limit: z.string().optional().describe("1..50, default 50"),
      cursor: z.string().optional(),
    }),
    responses: { 200: closedSessionPage, 400: requestValidation },
  }),
  defineRoute({
    operationId: "getReviewSession",
    method: "get",
    path: "/api/review-sessions/{sessionId}",
    summary: "Read one Review Session.",
    tags: ["review-sessions"],
    params: sessionParams,
    responses: { 200: reviewSession, 400: detailError, 404: detailError },
  }),
  defineRoute({
    operationId: "recreateReviewSession",
    method: "post",
    path: "/api/review-sessions/{sessionId}/recreate",
    summary: "Recreate a closed Review Session from its server-owned ready artifacts (Idempotency-Key required).",
    tags: ["review-sessions"],
    params: sessionParams,
    body: recreateSessionRequest,
    responses: {
      200: recreateSessionResponse,
      201: recreateSessionResponse,
      400: requestValidation,
      404: detailError,
      409: recreateNotRebuildableError,
    },
  }),
  defineRoute({
    operationId: "getStreamConfig",
    method: "get",
    path: "/api/review-sessions/{sessionId}/stream-config",
    summary: "Browser bootstrap for Kit streaming: canonical trace, WebRTC endpoints, stage composition.",
    tags: ["review-sessions"],
    params: sessionParams,
    responses: { 200: streamConfigResponse, 400: detailError, 404: detailError, 409: detailError },
  }),
  defineRoute({
    operationId: "reportFirstFrame",
    method: "post",
    path: "/api/review-sessions/{sessionId}/first-frame",
    summary: "Console reports the first real video frame for a session.",
    tags: ["review-sessions"],
    params: sessionParams,
    responses: { 200: firstFrameResponse, 400: detailError, 404: detailError, 409: detailError, 500: detailError },
  }),
  defineRoute({
    operationId: "closeReviewSession",
    method: "post",
    path: "/api/review-sessions/{sessionId}/close",
    summary: "Close a Review Session (resumable checkpointed close).",
    tags: ["review-sessions"],
    params: sessionParams,
    body: closeSessionRequest,
    responses: { 200: reviewSession, 400: detailError, 404: detailError },
  }),
  defineRoute({
    operationId: "recordSessionActivity",
    method: "post",
    path: "/api/review-sessions/{sessionId}/activity",
    summary: "Viewer activity heartbeat for idle reclaim (requires an active viewer lease).",
    tags: ["review-sessions"],
    auth: "user",
    params: sessionParams,
    body: sessionActivityRequest,
    responses: { 200: sessionActivityResponse, 400: requestValidation, 404: detailError, 409: detailError, ...userAuth },
  }),
  defineRoute({
    operationId: "getSessionIdleStatus",
    method: "get",
    path: "/api/review-sessions/{sessionId}/idle-status",
    summary: "Idle countdown state for one session.",
    tags: ["review-sessions"],
    params: sessionParams,
    responses: { 200: sessionIdleStatusResponse, 400: detailError, 404: detailError },
  }),
  defineRoute({
    operationId: "enqueueIssueSnapshot",
    method: "post",
    path: "/api/review-sessions/{sessionId}/issue-snapshot",
    summary: "Enqueue a metadata-only issue snapshot to the cloud callback outbox.",
    tags: ["review-sessions"],
    params: sessionParams,
    body: issueSnapshotRequest,
    responses: {
      202: issueSnapshotAccepted,
      400: requestValidation,
      404: detailError,
      409: namedError,
      422: detailError,
      502: namedError,
    },
  }),

  // ── Viewer leases ──────────────────────────────────────────────────────────
  defineRoute({
    operationId: "claimViewerLease",
    method: "post",
    path: "/api/review-sessions/{sessionId}/viewer-leases/claim",
    summary: "Claim the editor (primary) or a spectator viewer lease.",
    tags: ["viewer-leases"],
    auth: "user",
    params: sessionParams,
    body: claimViewerLeaseRequest,
    responses: { 200: claimViewerLeaseResponse, 400: requestValidation, 404: detailError, 409: detailError, 503: detailError, ...userAuth },
  }),
  defineRoute({
    operationId: "heartbeatViewerLease",
    method: "post",
    path: "/api/review-sessions/{sessionId}/viewer-leases/{leaseId}/heartbeat",
    summary: "Keep a viewer lease alive and report stage/DataChannel evidence.",
    tags: ["viewer-leases"],
    auth: "user",
    params: leaseParams,
    body: heartbeatViewerLeaseRequest,
    responses: { 200: heartbeatViewerLeaseResponse, 400: requestValidation, 404: detailError, 409: detailError, 503: detailError, ...userAuth },
  }),
  defineRoute({
    operationId: "releaseViewerLease",
    method: "post",
    path: "/api/review-sessions/{sessionId}/viewer-leases/{leaseId}/release",
    summary: "Release a viewer lease.",
    tags: ["viewer-leases"],
    auth: "user",
    params: leaseParams,
    body: releaseViewerLeaseRequest,
    responses: { 200: publicViewerLease, 400: requestValidation, 404: detailError, 503: detailError, ...userAuth },
  }),
  defineRoute({
    operationId: "getViewerLeaseStatus",
    method: "get",
    path: "/api/review-sessions/{sessionId}/viewer-leases/status",
    summary: "Lease occupancy and Stage Binding Transaction summary for the caller.",
    tags: ["viewer-leases"],
    auth: "user",
    params: sessionParams,
    responses: { 200: viewerLeaseStatusResponse, 400: detailError, 404: detailError, ...userAuth },
  }),

  // ── Stage Binding Transaction ──────────────────────────────────────────────
  defineRoute({
    operationId: "preauthorizeStageBinding",
    method: "post",
    path: "/api/review-sessions/{sessionId}/stage-binding",
    summary: "Preauthorize one stage composition; returns a pending Stage Binding Transaction.",
    tags: ["stage-binding"],
    auth: "user",
    params: sessionParams,
    body: stageBindingPreauthorizationRequest,
    responses: {
      200: stageBindingPreauthorizationResponse,
      400: requestValidation,
      404: detailError,
      409: detailError,
      503: detailError,
      ...userAuth,
    },
  }),
  defineRoute({
    operationId: "cancelStageBinding",
    method: "post",
    path: "/api/review-sessions/{sessionId}/stage-binding-cancellations",
    summary: "Cancel a pending Stage Binding Transaction by client request id.",
    tags: ["stage-binding"],
    auth: "user",
    params: sessionParams,
    body: stageBindingCancellationRequest,
    responses: {
      200: stageBindingCancellationResponse,
      400: requestValidation,
      404: detailError,
      409: z.union([stageBindingNotAbortableError, detailError]),
      503: detailError,
      ...userAuth,
    },
  }),

  // ── A4 3D handoff ──────────────────────────────────────────────────────────
  defineRoute({
    operationId: "createA4Handoff",
    method: "post",
    path: "/api/review-sessions/{sessionId}/a4-handoffs",
    summary: "Create an A4 focus/highlight handoff intent from governance evidence proofs.",
    tags: ["a4"],
    auth: "user",
    params: sessionParams,
    body: a4HandoffCreateRequest,
    responses: {
      201: a4HandoffCreateResponse,
      400: errorCodeError,
      401: z.union([detailError, errorCodeError]),
      403: z.union([detailError, errorCodeError]),
      409: a4HandoffEvidenceRejected,
      503: errorCodeError,
    },
  }),
  defineRoute({
    operationId: "consumeA4Handoff",
    method: "post",
    path: "/api/review-sessions/{sessionId}/a4-handoffs/{handoffId}/consume",
    summary: "Consume an A4 handoff intent once inside the 3D workspace.",
    tags: ["a4"],
    auth: "user",
    params: z.object({ sessionId: sessionIdParam, handoffId: z.string().min(1).max(200) }),
    responses: {
      200: a4HandoffConsumeResponse,
      400: errorCodeError,
      401: z.union([detailError, errorCodeError]),
      403: z.union([detailError, errorCodeError]),
      409: errorCodeError,
      503: errorCodeError,
    },
  }),

  // ── Conversion ─────────────────────────────────────────────────────────────
  defineRoute({
    operationId: "listConversionRecords",
    method: "get",
    path: "/api/conversion/records",
    summary: "ConversionLedger operator projection.",
    tags: ["conversion"],
    query: z.object({ limit: z.string().optional() }),
    responses: { 200: conversionRecordsResponse },
  }),
  defineRoute({
    operationId: "openReadyModelReviewSession",
    method: "post",
    path: "/api/conversion/records/{readyModelId}/review-session",
    summary: "Open, create or reuse a Review Session for a MinIO ready model.",
    tags: ["conversion"],
    auth: "operator",
    params: z.object({ readyModelId: readyModelIdParam }),
    body: readyReviewIntentRequest,
    responses: {
      200: readyReviewSessionResponse,
      400: z.union([errorCodeError, validationError]),
      404: errorCodeError,
      409: errorCodeError,
      502: errorCodeError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "prioritizeConversionJob",
    method: "post",
    path: "/api/conversion/jobs/{ifcReadyJobId}/prioritize",
    summary: "Move a queued ifc-ready job to the front of the serial dispatch queue.",
    tags: ["conversion"],
    auth: "operator",
    params: z.object({ ifcReadyJobId: safeJobIdParam }),
    body: conversionControlRequest,
    responses: {
      200: conversionPrioritizeResponse,
      400: detailError,
      404: detailError,
      409: detailError,
      422: detailError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "retryConversionJob",
    method: "post",
    path: "/api/conversion/jobs/{ifcReadyJobId}/retry",
    summary: "Re-queue a failed or dropped ifc-ready job.",
    tags: ["conversion"],
    auth: "operator",
    params: z.object({ ifcReadyJobId: safeJobIdParam }),
    body: conversionControlRequest,
    responses: {
      200: conversionRetryResponse,
      400: detailError,
      404: detailError,
      409: z.union([conversionRetryConflict, detailError]),
      422: detailError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "setConversionWatch",
    method: "put",
    path: "/api/conversion/watch",
    summary: "Enable or disable the MinIO Watch Surface loop.",
    tags: ["conversion"],
    auth: "operator",
    body: minioWatchToggleRequest,
    responses: {
      200: minioWatchStatusView,
      400: detailError,
      409: detailError,
      422: detailError,
      500: detailError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "triggerConversion",
    method: "post",
    path: "/api/conversion/trigger",
    summary: "Manually trigger (or force re-trigger) conversion for one MinIO object key.",
    tags: ["conversion"],
    auth: "operator",
    body: conversionTriggerRequest,
    responses: {
      200: conversionTriggerResponse,
      202: conversionTriggerResponse,
      400: anyError,
      409: errorCodeError,
      502: anyError,
      503: detailError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "getConversionQualityMetrics",
    method: "get",
    path: "/api/conversions/{conversionJobId}/quality-metrics",
    summary: "Quality metrics summary for one conversion job (read through the conversion authority).",
    tags: ["conversion"],
    params: z.object({ conversionJobId: safeJobIdParam }),
    responses: { 200: conversionQualityMetricsResponse, 400: detailError, 403: detailError, 404: detailError, 502: detailError },
  }),

  // ── IFC-ready intake ───────────────────────────────────────────────────────
  defineRoute({
    operationId: "acceptIfcReady",
    method: "post",
    path: "/api/external/ifc-ready",
    summary: "IFC-ready intake (external worker or MinIO watcher self-post); idempotent by key.",
    tags: ["ifc-ready"],
    auth: "external",
    body: ifcReadyIntakeRequest,
    responses: {
      200: ifcReadyIntakeReplay,
      202: ifcReadyIntakeAccepted,
      400: requestValidation,
      401: detailError,
      403: detailError,
      502: ifcReadyDownloadFailed,
    },
  }),
  defineRoute({
    operationId: "listIfcReadyJobs",
    method: "get",
    path: "/api/external/ifc-ready",
    summary: "Recent ifc-ready intake jobs with lifecycle and failure projection.",
    tags: ["ifc-ready"],
    query: z.object({ limit: z.string().optional() }),
    responses: { 200: ifcReadyListResponse },
  }),
  defineRoute({
    operationId: "getIfcReadyJob",
    method: "get",
    path: "/api/external/ifc-ready/{jobId}",
    summary: "One ifc-ready intake job with artifact health and recovery action.",
    tags: ["ifc-ready"],
    params: z.object({ jobId: safeJobIdParam }),
    responses: { 200: ifcReadyDetailResponse, 400: detailError, 404: detailError },
  }),
  defineRoute({
    operationId: "openIfcReadyReviewSession",
    method: "post",
    path: "/api/external/ifc-ready/{jobId}/review-session",
    summary: "Open or attach the Review Session for a converted ifc-ready job.",
    tags: ["ifc-ready"],
    params: z.object({ jobId: safeJobIdParam }),
    responses: {
      200: ifcReadyReviewSessionOpen,
      400: detailError,
      404: detailError,
      409: ifcReadyReviewSessionConflict,
      502: ifcReadyReviewSessionConflict,
    },
  }),
  defineRoute({
    operationId: "getMinioWatchStatus",
    method: "get",
    path: "/api/external/minio-watch/status",
    summary: "MinIO Watch Surface status counters.",
    tags: ["minio"],
    responses: { 200: minioWatchStatusView },
  }),
  defineRoute({
    operationId: "listMinioObjects",
    method: "get",
    path: "/api/minio/objects",
    summary: "Browse the governed MinIO bucket (folder or flat listing).",
    tags: ["minio"],
    query: z.object({
      prefix: z.string().optional(),
      delimiter: z.literal("/").optional(),
      refresh: z.string().optional(),
      force: z.string().optional(),
    }),
    responses: { 200: minioObjectsResponse, 400: namedError, 502: namedError },
  }),

  // ── Lineage ────────────────────────────────────────────────────────────────
  defineRoute({
    operationId: "lookupLineageSourceBundles",
    method: "get",
    path: "/api/lineage/source-bundles",
    summary: "Find governed source bundles whose verified manifest references one MinIO IFC object.",
    tags: ["lineage"],
    query: z.object({
      source_ifc_bucket: z.string(),
      source_ifc_key: z.string(),
      source_ifc_etag: z.string(),
    }),
    responses: { 200: sourceBundleLookupResponse, 400: namedError },
  }),
  defineRoute({
    operationId: "listLineageConversionReports",
    method: "get",
    path: "/api/lineage/conversion-reports",
    summary: "Alignment reports produced by conversions, newest first; optionally for one MinIO IFC object.",
    tags: ["lineage"],
    query: z.object({
      source_ifc_key: z.string().optional(),
      limit: z.string().optional(),
    }),
    responses: { 200: lineageConversionReportList, 400: namedError, 503: namedError },
  }),
  defineRoute({
    operationId: "getLineageConversionReport",
    method: "get",
    path: "/api/lineage/conversion-reports/{conversionJobId}",
    summary: "One conversion's alignment report summary, file digests and MinIO upload outcome.",
    tags: ["lineage"],
    params: z.object({ conversionJobId: safeJobIdParam }),
    responses: { 200: lineageConversionReport, 400: namedError, 404: namedError, 503: namedError },
  }),
  defineRoute({
    operationId: "listLineageConversionReportDifferences",
    method: "get",
    path: "/api/lineage/conversion-reports/{conversionJobId}/differences",
    summary: "One page of one difference set from a generated alignment report.",
    tags: ["lineage"],
    params: z.object({ conversionJobId: safeJobIdParam }),
    query: z.object({
      set: lineageDifferenceSet,
      offset: z.string().optional(),
      limit: z.string().optional(),
    }),
    responses: { 200: lineageConversionReportDifferences, 400: namedError, 404: namedError, 413: namedError, 503: namedError },
  }),

  // ── Callback outbox ────────────────────────────────────────────────────────
  defineRoute({
    operationId: "getCallbackOutboxSummary",
    method: "get",
    path: "/api/callback-outbox/summary",
    summary: "Operator summary of the cloud callback outbox (metadata only).",
    tags: ["outbox"],
    query: z.object({ limit: z.string().optional().describe("1..200") }),
    responses: { 200: callbackOutboxSummary, 400: detailError },
  }),

  // ── CFD wind runs (building-energy-cfd-p2-contract.md §3.2; payloads = tests/contracts/cfd-run-*-v1) ──
  defineRoute({
    operationId: "createCfdRun",
    method: "post",
    path: "/api/cfd/runs",
    summary: "Start a CFD wind run for one converted model (design comparison only); coordinator binds the exact model.usdc sha256.",
    tags: ["cfd"],
    auth: "operator",
    body: cfdRunCreateRequest,
    responses: {
      200: cfdRunStatusDocument,
      202: cfdRunStatusDocument,
      400: errorCodeError,
      404: errorCodeError,
      409: errorCodeError,
      /** S8: compute_cap_exceeded — the estimate exceeds CFD_MAX_CELLS_PER_DIRECTION; nothing was queued. */
      422: errorCodeError,
      502: errorCodeError,
      503: errorCodeError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "getCfdOptions",
    method: "get",
    path: "/api/cfd/options",
    summary: "S8: defaults, contract bounds, presets and host limits for the CFD settings form (cfd-options/v1 from the streaming job service).",
    tags: ["cfd"],
    responses: { 200: cfdOptionsDocument, 502: errorCodeError, 503: errorCodeError },
  }),
  defineRoute({
    operationId: "estimateCfdRun",
    method: "post",
    path: "/api/cfd/estimates",
    summary: "S8: read-only cell/time estimate for a CFD run before it is submitted (cfd-estimate/v1); nothing is stored.",
    tags: ["cfd"],
    body: cfdEstimateRequest,
    responses: { 200: cfdEstimate, 400: errorCodeError, 404: errorCodeError, 409: errorCodeError, 502: errorCodeError, 503: errorCodeError },
  }),
  defineRoute({
    operationId: "listCfdRuns",
    method: "get",
    path: "/api/cfd/runs",
    summary: "Ledger of CFD runs (refreshed from the streaming job service when enabled).",
    tags: ["cfd"],
    query: cfdRunListQuery,
    responses: { 200: cfdRunListResponse, 400: errorCodeError },
  }),
  defineRoute({
    operationId: "getCfdRun",
    method: "get",
    path: "/api/cfd/runs/{runId}",
    summary: "Status of one CFD run (streaming cfd-run-status/v1 plus ledger projection).",
    tags: ["cfd"],
    params: cfdRunParams,
    responses: { 200: cfdRunDetailResponse, 404: errorCodeError, 502: errorCodeError, 503: errorCodeError },
  }),
  defineRoute({
    operationId: "getCfdRunResult",
    method: "get",
    path: "/api/cfd/runs/{runId}/result",
    summary: "cfd-run-result/v1 with overlay/run-record URLs rewritten to the public streaming origin.",
    tags: ["cfd"],
    params: cfdRunParams,
    responses: { 200: cfdRunResult, 404: errorCodeError, 409: errorCodeError, 502: errorCodeError, 503: errorCodeError },
  }),
  defineRoute({
    operationId: "getCfdRunExclusions",
    method: "get",
    path: "/api/cfd/runs/{runId}/exclusions",
    summary: "Exclusion list (cfd-exclusion-list/v1) of one CFD run.",
    tags: ["cfd"],
    params: cfdRunParams,
    responses: { 200: cfdRunExclusions, 404: errorCodeError, 409: errorCodeError, 502: errorCodeError, 503: errorCodeError },
  }),
  defineRoute({
    operationId: "cancelCfdRun",
    method: "post",
    path: "/api/cfd/runs/{runId}/cancel",
    summary: "Cancel a queued or running CFD run (409 when the run is already terminal).",
    tags: ["cfd"],
    auth: "operator",
    params: cfdRunParams,
    responses: { 200: cfdRunStatusDocument, 404: errorCodeError, 409: errorCodeError, 502: errorCodeError, 503: errorCodeError, ...operatorGuard },
  }),
  defineRoute({
    operationId: "createCfdFindings",
    method: "post",
    path: "/api/cfd/runs/{runId}/findings",
    summary: "S6 A1 finding: open a governance issue (existing /api/issues, annotation kind) for every ready direction whose pedestrian-plane |U|max exceeds the threshold; idempotent per (run, direction, threshold).",
    tags: ["cfd"],
    auth: "operator",
    params: cfdRunParams,
    body: cfdFindingRequest,
    responses: { 200: cfdFindingResponse, 201: cfdFindingResponse, 400: errorCodeError, 404: errorCodeError, 409: errorCodeError, 502: errorCodeError, 503: errorCodeError, ...operatorGuard },
  }),
  defineRoute({
    operationId: "registerCfdOverlay",
    method: "post",
    path: "/api/review-sessions/{sessionId}/cfd-overlays",
    summary: "Register one finished CFD direction as an overlay ArtifactBinding on the session; load it with the existing stage-binding flow.",
    tags: ["cfd"],
    auth: "operator",
    params: sessionParams,
    body: cfdOverlayRegistrationRequest,
    responses: {
      200: cfdOverlayRegistrationResponse,
      201: cfdOverlayRegistrationResponse,
      400: errorCodeError,
      404: errorCodeError,
      409: errorCodeError,
      502: errorCodeError,
      503: errorCodeError,
      ...operatorGuard,
    },
  }),
  defineRoute({
    operationId: "removeCfdOverlay",
    method: "delete",
    path: "/api/review-sessions/{sessionId}/cfd-overlays/{bindingId}",
    summary: "Remove a CFD overlay binding from the session (files are kept in the job store).",
    tags: ["cfd"],
    auth: "operator",
    params: cfdOverlayParams,
    responses: { 200: cfdOverlayRemovalResponse, 404: errorCodeError, ...operatorGuard },
  }),
] as const;

export type BrowserContract = typeof browserContract;
export type BrowserRoute = BrowserContract[number];
export type BrowserOperationId = BrowserRoute["operationId"];
