param([ValidateSet('Audit','Apply','Recover','Verify')][string]$Mode='Audit',[Parameter(Mandatory)][string]$CodexHome,[string]$CandidatePath,[string[]]$ToolPath,[string]$AllowlistPath,[string]$SealPath,[string]$ExpectedOwnerSid)
. "$PSScriptRoot/../lib/codex-governance/Maintenance.Common.ps1"; . "$PSScriptRoot/../lib/codex-governance/Maintenance.Transaction.ps1"; . "$PSScriptRoot/../lib/codex-governance/Maintenance.Health.ps1"
function New-MaintenanceReport { param($mode,$status,$ids,$journal,$health,$rollback,$next); [pscustomobject][ordered]@{runId=[guid]::NewGuid().ToString();mode=$mode;status=$status;candidateIds=@($ids);journalPath=$journal;health=$health;rollback=$rollback;nextStep=$next} }
function Invoke-MaintenanceAudit { param([string]$Root,[string]$Candidate,$Allowlist)
 $ids=@(); if($Candidate){$c=Get-Content $Candidate -Raw|ConvertFrom-Json; if($c.PSObject.Properties.Name -contains 'createdAtUtc' -and ([DateTime]::Parse($c.createdAtUtc) -lt [DateTime]::UtcNow.AddHours(-24))){throw 'Candidate is stale'}; if($Allowlist){ . "$PSScriptRoot/../lib/codex-governance/Maintenance.Trust.ps1"; New-TrustedInventory $c $Allowlist | Out-Null }; $id=if($c.sourceId){$c.sourceId}else{[guid]::NewGuid().ToString()}; $ids+=$id; Write-AtomicJson -Path (Join-Path $Root ("candidate-$id.json")) -InputObject $c -Root $Root }
 New-MaintenanceReport Audit 'audited' $ids (Join-Path $Root 'maintenance-journal.json') ([pscustomobject]@{Status='pass'}) ([pscustomobject]@{Complete=$true}) 'Review candidate and run Apply'
}
function Invoke-MaintenanceApply { param([string]$Root,[string]$Candidate,$Allowlist)
 if(-not $Candidate){throw 'CandidatePath is required for Apply'}; $c=Get-Content $Candidate -Raw|ConvertFrom-Json; if($c.createdAtUtc -and ([DateTime]::Parse($c.createdAtUtc) -lt [DateTime]::UtcNow.AddHours(-24))){throw 'Candidate is stale'}; if($Allowlist){. "$PSScriptRoot/../lib/codex-governance/Maintenance.Trust.ps1"; New-TrustedInventory $c $Allowlist|Out-Null}
 $snap=Join-Path $Root ('.snapshot-'+[guid]::NewGuid()); New-Item $snap -ItemType Directory|Out-Null; Get-ChildItem $Root -Force | Where-Object {$_.Name -notin @('maintenance.lock','maintenance-journal.json') -and $_.FullName -ne $snap}|Copy-Item -Destination $snap -Recurse -Force; if(-not (Test-Path $snap)){throw 'Snapshot creation failed'}
 $j=Join-Path $Root 'maintenance-journal.json'; Write-JournalPhase $j applying @{TargetPath=$Root;SnapshotPath=$snap} -Root $Root|Out-Null
 New-MaintenanceReport Apply 'staged' @($c.sourceId) $j ([pscustomobject]@{Status='pass'}) ([pscustomobject]@{Complete=$true}) 'Apply callback required; run Verify'
}
function Invoke-MaintenanceRecover { param([string]$Root)
 $j=Join-Path $Root 'maintenance-journal.json'; if(-not (Test-Path $j)){return New-MaintenanceReport Recover 'noop' @() $j ([pscustomobject]@{Status='noop'}) ([pscustomobject]@{Complete=$true}) 'No recovery required'}; $r=Resume-InterruptedTransaction -JournalPath $j -CodexHome $Root; New-MaintenanceReport Recover $r.Status @() $j ([pscustomobject]@{Status=$r.Status}) ([pscustomobject]@{Complete=($r.Status -eq 'recovered')}) 'Run Verify'
}
function Invoke-MaintenanceVerify { param([string]$Root,[hashtable]$Baseline=@{},[hashtable]$Actual=@{})
 $h=Invoke-MaintenanceHealthGate -Baseline $Baseline -Actual $Actual -RollbackComplete:$true; $disabled=$h.Status -ne 'pass'; if($disabled){Write-AtomicJson -Path (Join-Path $Root 'apply-disabled.json') -InputObject @{disabled=$true;reason=$h.Status;timestamp=[DateTime]::UtcNow.ToString('o')} -Root $Root}; $s=if($disabled){'failed'}else{'verified'}; $next=if($disabled){'Apply disabled; recover cohort'}else{'Complete'}; $r=[pscustomobject]@{Complete=$h.RollbackComplete;Disabled=$disabled}; $report=New-MaintenanceReport Verify $s @() (Join-Path $Root 'maintenance-journal.json') $h $r $next; $report | Add-Member NoteProperty disabled $disabled; $report
}
$root=[IO.Path]::GetFullPath($CodexHome); $hasAllow=[bool]$AllowlistPath; $hasSeal=[bool]$SealPath; $hasSid=[bool]$ExpectedOwnerSid; $trustCount=([int]$hasAllow)+([int]$hasSeal)+([int]$hasSid); if($trustCount -ne 0 -and $trustCount -ne 3){throw 'AllowlistPath, SealPath, and ExpectedOwnerSid must be supplied together'}; $allow=$null; Assert-MaintenanceStartup -CodexHome $root -ToolPath $ToolPath -AllowlistPath $AllowlistPath -SealPath $SealPath -ExpectedSid $ExpectedOwnerSid | Out-Null; if($AllowlistPath){. "$PSScriptRoot/../lib/codex-governance/Maintenance.Trust.ps1"; $allow=Read-SealedAllowlist $AllowlistPath $SealPath $ExpectedOwnerSid}; $lock=Enter-MaintenanceLock -Root $root
try { switch($Mode){'Audit'{Invoke-MaintenanceAudit $root $CandidatePath $allow};'Apply'{Invoke-MaintenanceApply $root $CandidatePath $allow};'Recover'{Invoke-MaintenanceRecover $root};'Verify'{Invoke-MaintenanceVerify $root}} } finally {$lock.Dispose()}
